name: 'goto-velociraptor'
description: 'Sends velociraptors if `goto` statements are added. xkcd.com/292'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
outputs:
  gotos: # output will be available to future steps
    description: 'Either `True` if a `goto` statement was added, `False` otherwise.'
runs:
  using: 'node12'
  main: 'dist/index.js'
