name: "goto-raptor"
description: "Sends velociraptors if `goto` statements are added. xkcd.com/292"
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    default: ${{ github.token }}
outputs:
  gotos: # output will be available to future steps
    description: "Either `True` if a `goto` statement was added, `False` otherwise."
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "check"
  color: "orange"
