name: "Re-package after dependabot"
on:
  pull_request:
    branches:
      - main

jobs:
  repackage:
    name: "Re-package dist/* and commit after dependabot updates"
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the new packages.
        # not `npm ci` because we've changed our dependencies.
        run: npm install
      - name: Format, lint, test, and package.
        run: npm run all
      - name: See what changed
        run: git status --porcelain
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Commit updated dist/* files
        uses: EndBug/add-and-commit@v6
        with:
          branch: ${GITHUB_REF##*/}
          add: dist
          author_name: Nick Crews
          author_email: nicholas.b.crews@gmail.com
          message: "Re-package dist/* after updating dependencies"
      - name: "Ensure there are no other unstaged changes lingering"
        run: git diff --quiet --exit-code
